spring:
  application:
    name: my-bank
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mybank
    username: mybank
    password: mybank
  jpa:
    show-sql: true
    open-in-view: false

  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    ignore-missing-migrations: true
    out-of-order: true

transfer:
  rules:
    SAME_BANK:
      tax: 0
    DIFFERENT_BANK:
      tax: 5
      limit: 1000
    SAME_CUSTOMER:
      tax: 1
      limit: 5000

server:
  port: 1981